### ISSUE TITLE
Horizon Throwing 404

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1132]
Visit the page https://develop.bpm4.qa.processmaker.net/admin/queues/recent-jobs

Click on any failed job to get the wrong link.

![image](https://user-images.githubusercontent.com/535300/50703227-4bdbf580-1008-11e9-8be4-fb6b15f8f093.png)

Bad Link (/horizon/failed/158) should be /admin/queues/failed/158

**Comment by nolanpro** [comment]
@velkymx I can't reproduce locally, can you check again? Might have been fixed by #1118

**Comment by velkymx** [comment]
Visit the page https://develop.bpm4.qa.processmaker.net/admin/queues/recent-jobs

Click on any failed job to get the wrong link. 

![screenshot 2019-01-04 10 03 35](https://user-images.githubusercontent.com/535300/50703182-2ea72700-1008-11e9-9c58-3ac369a2e010.png)

**Comment by velkymx** [comment]
@nolanpro I've updated the description with more details. This is not fixed.

**Comment by velkymx** [comment]
Bug in Laravel

**Comment by velkymx** [comment]
I'm still encountering this issue. It needs to be fixed - maybe a javascript that replaces the URL????

**Comment by tdondich** [comment]
We should determine if a newer version of Laravel Horizon may solve this.  Please see: https://github.com/laravel/horizon/releases

**Comment by nolanpro** [comment]
@tdondich sadly it is not. Others have also tried to get PRs on this repo in to no avail. https://github.com/laravel/horizon/pull/513#issuecomment-464747214

**Comment by velkymx** [comment]
Let's just do a work around and update the URLS on page load with JavaScript and get on with it. Who's issue it is does not fix this bug.

**Comment by nolanpro** [comment]
@velkymx couldn't figure out how to modify the html directly. This PR is for a workaround using axios interceptors. Let me know what you think.

**Comment by velkymx** [comment]
We'll see how they work. Thanks!
