### ISSUE TITLE
Find Users in Group or Groups for User

### ISSUE THREAD

**Issue by josemaldonad0** [ProcessMaker/bpm#954]
The ' Groups' icon on the User list does not work -does not do anything. 
Similarly, the 'Users' icon on the group list does not work. 

As a result, one cannot really find which users are in which group.

**Comment by josemaldonad0** [comment]
Only way I see to associate a user to a group is during User creation.

Also, Group tab in the Edit user does not show anything. 

However, user count in the group list does seem to reflect, so the links do seem to be made, just an issue with displaying them.

**Comment by danloa** [comment]
@velkymx this issue is already resolved:
- The groups icon has been removed from the interface
- The users icon is removed from the groups list. The list of users within a group is available in the "group members" tab when editing a group

**Comment by ryancooley** [comment]
Confirmed as resolved.

**Comment by PMQABen** [comment]
Has this been resolved? When looking inside the `develop` branch, the Group tab inside "edit user" still appears, and still does not show anything.

**Comment by ryancooley** [comment]
@PMQABen So you're not seeing the below interface?

![screen shot 2019-01-22 at 1 11 16 pm](https://user-images.githubusercontent.com/867714/51565613-41628e00-1e47-11e9-93dc-53bc51344c18.png)

**Comment by ryancooley** [comment]
Note for future reference: was resolved by running `npm run dev`.
